{-# LANGUAGE DeriveDataTypeable #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.7.0-dev)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module Thrift.ContentProvider where
import Prelude ( Bool(..), Enum, Double, String, Maybe(..),
                 Eq, Show, Ord,
                 return, length, IO, fromIntegral, fromEnum, toEnum,
                 (&&), (||), (==), (++), ($), (-) )

import Control.Exception
import Data.ByteString.Lazy
import Data.Int
import Data.Typeable ( Typeable )
import qualified Data.Map as Map
import qualified Data.Set as Set

import Thrift


import Thrift.Content_Types
import qualified Thrift.ContentProvider_Iface as Iface
-- HELPER FUNCTIONS AND STRUCTURES --

data DownloadMesh_args = DownloadMesh_args{f_DownloadMesh_args_name :: Maybe String} deriving (Show,Eq,Ord,Typeable)
write_DownloadMesh_args oprot record = do
  writeStructBegin oprot "DownloadMesh_args"
  case f_DownloadMesh_args_name record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("name",T_STRING,1)
    writeString oprot _v
    writeFieldEnd oprot}
  writeFieldStop oprot
  writeStructEnd oprot
read_DownloadMesh_args_fields iprot record = do
  (_,_t41,_id42) <- readFieldBegin iprot
  if _t41 == T_STOP then return record else
    case _id42 of 
      1 -> if _t41 == T_STRING then do
        s <- readString iprot
        read_DownloadMesh_args_fields iprot record{f_DownloadMesh_args_name=Just s}
        else do
          skip iprot _t41
          read_DownloadMesh_args_fields iprot record
      _ -> do
        skip iprot _t41
        readFieldEnd iprot
        read_DownloadMesh_args_fields iprot record
read_DownloadMesh_args iprot = do
  _ <- readStructBegin iprot
  record <- read_DownloadMesh_args_fields iprot (DownloadMesh_args{f_DownloadMesh_args_name=Nothing})
  readStructEnd iprot
  return record
data DownloadMesh_result = DownloadMesh_result{f_DownloadMesh_result_success :: Maybe Mesh} deriving (Show,Eq,Ord,Typeable)
write_DownloadMesh_result oprot record = do
  writeStructBegin oprot "DownloadMesh_result"
  case f_DownloadMesh_result_success record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("success",T_STRUCT,0)
    write_Mesh oprot _v
    writeFieldEnd oprot}
  writeFieldStop oprot
  writeStructEnd oprot
read_DownloadMesh_result_fields iprot record = do
  (_,_t46,_id47) <- readFieldBegin iprot
  if _t46 == T_STOP then return record else
    case _id47 of 
      0 -> if _t46 == T_STRUCT then do
        s <- (read_Mesh iprot)
        read_DownloadMesh_result_fields iprot record{f_DownloadMesh_result_success=Just s}
        else do
          skip iprot _t46
          read_DownloadMesh_result_fields iprot record
      _ -> do
        skip iprot _t46
        readFieldEnd iprot
        read_DownloadMesh_result_fields iprot record
read_DownloadMesh_result iprot = do
  _ <- readStructBegin iprot
  record <- read_DownloadMesh_result_fields iprot (DownloadMesh_result{f_DownloadMesh_result_success=Nothing})
  readStructEnd iprot
  return record
process_downloadMesh (seqid, iprot, oprot, handler) = do
  args <- read_DownloadMesh_args iprot
  readMessageEnd iprot
  rs <- return (DownloadMesh_result Nothing)
  res <- (do
    res <- Iface.downloadMesh handler (f_DownloadMesh_args_name args)
    return rs{f_DownloadMesh_result_success= Just res})
  writeMessageBegin oprot ("downloadMesh", M_REPLY, seqid);
  write_DownloadMesh_result oprot res
  writeMessageEnd oprot
  tFlush (getTransport oprot)
proc_ handler (iprot,oprot) (name,typ,seqid) = case name of
  "downloadMesh" -> process_downloadMesh (seqid,iprot,oprot,handler)
  _ -> do
    skip iprot T_STRUCT
    readMessageEnd iprot
    writeMessageBegin oprot (name,M_EXCEPTION,seqid)
    writeAppExn oprot (AppExn AE_UNKNOWN_METHOD ("Unknown function " ++ name))
    writeMessageEnd oprot
    tFlush (getTransport oprot)
process handler (iprot, oprot) = do
  (name, typ, seqid) <- readMessageBegin iprot
  proc_ handler (iprot,oprot) (name,typ,seqid)
  return True
